name: Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          
      - name: Build and run tests
        uses: actions/checkout@v3
        with:
          source_dir: ./src/tests
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test         
          
      - name: Generate docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./docs
          template: minami
          recurse: true

      - name: Push docs
        run: |
          cd docs
          git add -A
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Automated documentation"
          git push

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_HTML: true
          # VALIDATE_CSS: true
          # USE_FIND_ALGORITHM: true
          DEFAULT_BRANCH: "main"
          # DEFAULT_WORKSPACE: /src
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./src
